databases:
  default:
    connector: postgres
    host: gamerize-db.ced0losplrxx.us-east-2.rds.amazonaws.com
    port: 5432
    user: quinn
    password: wecSZfc3ZLHyC4u
    migrations: true
    rawAccess: true
