projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        dev: https://gamerize-476e004ca6.herokuapp.com/gamerize/dev
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
